# Generated by Django 3.1.3 on 2020-12-03 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('icao', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('callsign', models.CharField(blank=True, max_length=7, null=True)),
                ('squawk', models.CharField(blank=True, max_length=4, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('aircraft_type', models.CharField(blank=True, max_length=30, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=30, null=True)),
                ('aircraft_model', models.CharField(blank=True, max_length=100, null=True)),
                ('aircraft_manufacturer', models.CharField(blank=True, max_length=50, null=True)),
                ('aircraft_year', models.CharField(blank=True, max_length=4, null=True)),
                ('construction_number', models.CharField(blank=True, max_length=30, null=True)),
                ('aircraft_operator', models.CharField(blank=True, max_length=30, null=True)),
                ('aircraft_species', models.CharField(blank=True, choices=[(0, 'None'), (1, 'Land Plane'), (2, 'Sea Plane'), (3, 'Amphibian'), (4, 'Helicopter'), (5, 'Gyrocopter'), (6, 'Species Tiltwing'), (7, 'Ground Vehicle'), (8, 'Tower')], max_length=30, null=True)),
                ('engine_type', models.CharField(blank=True, choices=[(0, 'None'), (1, 'Piston'), (2, 'Turboprop'), (3, 'Jet'), (4, 'Electric')], max_length=30, null=True)),
                ('engine_mount', models.CharField(blank=True, choices=[(1, 'Unknown'), (1, 'Aft Mounted'), (2, 'Wing Buried'), (3, 'Fuselage Buried'), (4, 'Nose Mounted'), (5, 'Wing Mounted')], max_length=30, null=True)),
            ],
            options={
                'db_table': 'aircraft_table',
            },
        ),
        migrations.CreateModel(
            name='DataRecord',
            fields=[
                ('data_record_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('valid_position', models.BooleanField()),
                ('ground_speed', models.DecimalField(decimal_places=5, max_digits=20)),
                ('altitude', models.DecimalField(decimal_places=5, max_digits=20)),
                ('vertical_rate', models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True)),
                ('track', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('valid_track', models.BooleanField(blank=True, null=True)),
                ('tracked_seconds', models.CharField(blank=True, max_length=30, null=True)),
                ('count_messages', models.CharField(blank=True, max_length=30, null=True)),
                ('icao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aircraft.aircraft')),
            ],
            options={
                'db_table': 'data_record_table',
                'unique_together': {('timestamp', 'icao')},
            },
        ),
    ]
