# Generated by Django 3.1.3 on 2020-11-04 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('icao', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('callsign', models.CharField(blank=True, max_length=6)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('aircraft_type', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'db_table': 'aircraft_table',
            },
        ),
        migrations.CreateModel(
            name='DataRecord',
            fields=[
                ('timestamp', models.DateTimeField(primary_key=True, serialize=False)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('ground_speed', models.DecimalField(decimal_places=5, max_digits=20)),
                ('altitude', models.DecimalField(decimal_places=5, max_digits=20)),
                ('icao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aircraft.aircraft')),
            ],
            options={
                'db_table': 'data_record_table',
                'unique_together': {('timestamp', 'icao')},
            },
        ),
    ]
