# Generated by Django 3.1.3 on 2020-11-29 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='squawk',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='callsign',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
