# Generated by Django 3.1.3 on 2021-01-30 03:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('notif_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be E.164 format, e.x. '+999999999' with up to 15 digits", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('longitude1', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude1', models.DecimalField(decimal_places=6, max_digits=8)),
                ('longitude2', models.DecimalField(decimal_places=6, max_digits=9)),
                ('latitude2', models.DecimalField(decimal_places=6, max_digits=8)),
            ],
            options={
                'db_table': 'user_notif_table',
            },
        ),
    ]
