# Generated by Django 3.1.3 on 2020-12-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0002_auto_20201129_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircraft',
            name='aircraft_manufacturer',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='aircraft_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='aircraft_operator',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='aircraft_species',
            field=models.CharField(blank=True, choices=[(0, 'None'), (1, 'Land Plane'), (2, 'Sea Plane'), (3, 'Amphibian'), (4, 'Helicopter'), (5, 'Gyrocopter'), (6, 'Species Tiltwing'), (7, 'Ground Vehicle'), (8, 'Tower')], max_length=30),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='aircraft_year',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='construction_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='engine_mount',
            field=models.CharField(blank=True, choices=[(1, 'Unknown'), (1, 'Aft Mounted'), (2, 'Wing Buried'), (3, 'Fuselage Buried'), (4, 'Nose Mounted'), (5, 'Wing Mounted')], max_length=30),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='engine_type',
            field=models.CharField(blank=True, choices=[(0, 'None'), (1, 'Piston'), (2, 'Turboprop'), (3, 'Jet'), (4, 'Electric')], max_length=30),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='registration_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='datarecord',
            name='count_messages',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='datarecord',
            name='track',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datarecord',
            name='tracked_seconds',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='datarecord',
            name='valid_position',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datarecord',
            name='valid_track',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datarecord',
            name='vertical_rate',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
